services:
  # docker-getting-started:
  #   image: docker/getting-started
  #   container_name: PruebaDocker
  #   ports:
  #     - "8081:80"

  wordpress:
    image: wordpress
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: wordpressdb
  
  db:
    image: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: wordpressdb
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
